spring:
  application:
    name: stetho

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

stetho:
  urls:
    - name: "Google"
      url: "https://www.google.com"
    - name: "GitHub"
      url: "https://www.github.com"
    - name: "Badland"
      url: "https://badland"
    - name: "Linkedin"
      url: "https://www.linkedin.com/"

  check-interval: 5000

server:
  port: 8282
